
TYPE_MAPPING = {
    "headphones": ["electronics_store", "shopping_mall"],
    "earbuds": ["electronics_store", "shopping_mall"],
    "phone case": ["electronics_store", "cell_phone_store", "shopping_mall"],
    "running shoes": ["shoe_store", "sporting_goods_store", "clothing_store", "shopping_mall"],
    "burger": ["restaurant", "fast_food_restaurant", "barbecue_restaurant"],
    "coffee": ["cafe", "coffee_shop"],
    "haircut": ["barber_shop", "beauty_salon", "hair_salon"],
    "car": ["car_dealer", "car_repair", "gas_station"],
    "barber": ["barber_shop"], 
    "salon": ["beauty_salon", "hair_salon"],
    # Business
    "office": ["corporate_office"],
    "farm": ["farm"],
    "ranch": ["ranch"],
    # Culture
    "art gallery": ["art_gallery"],
    "museum": ["museum"],
    "theater": ["performing_arts_theater", "movie_theater"],
    # Education
    "library": ["library"],
    "school": ["school", "primary_school", "secondary_school", "preschool"],
    "university": ["university"],
    # Entertainment and Recreation
    "amusement park": ["amusement_park", "water_park"],
    "aquarium": ["aquarium"],
    "casino": ["casino"],
    "park": ["park", "national_park", "state_park", "dog_park"],
    "zoo": ["zoo"],
    # Food and Drink
    "bakery": ["bakery"],
    "bar": ["bar", "night_club", "pub", "wine_bar"],
    "cafe": ["cafe", "coffee_shop", "tea_house"],
    "deli": ["deli"],
    "dessert": ["dessert_shop", "ice_cream_shop", "candy_store"],
    "pizza": ["pizza_restaurant"],
    "sushi": ["sushi_restaurant"],
    "vegan food": ["vegan_restaurant"],
    # Health and Wellness
    "dentist": ["dentist", "dental_clinic"],
    "doctor": ["doctor", "hospital"],
    "pharmacy": ["pharmacy", "drugstore"],
    "spa": ["spa", "wellness_center"],
    "gym": ["gym", "fitness_center"],
    "yoga": ["yoga_studio"],
    # Lodging
    "hotel": ["hotel", "lodging", "motel", "bed_and_breakfast", "guest_house"],
    "campground": ["campground", "rv_park"],
    # Shopping
    "auto parts": ["auto_parts_store"],
    "bike shop": ["bicycle_store"],
    "book store": ["book_store"],
    "cell phone": ["cell_phone_store"],
    "clothing": ["clothing_store", "shoe_store", "department_store", "discount_store"],
    "convenience store": ["convenience_store"],
    "electronics": ["electronics_store"],
    "furniture": ["furniture_store", "home_goods_store"],
    "grocery": ["grocery_store", "supermarket", "asian_grocery_store"],
    "hardware": ["hardware_store", "home_improvement_store"],
    "jewelry": ["jewelry_store"],
    "liquor store": ["liquor_store"],
    "pet store": ["pet_store"],
    "shopping mall": ["shopping_mall"],
    "sporting goods": ["sporting_goods_store"],
    "store": ["store"], 
    # Transportation
    "airport": ["airport", "international_airport"],
    "bus station": ["bus_station", "bus_stop"],
    "train station": ["train_station", "light_rail_station", "subway_station"],
}